testing again "added some lines for run "

diff --git a/.github/workflows/terraform.yml b/.github/workflows/terraform.yml
--- a/.github/workflows/terraform.yml
+++ b/.github/workflows/terraform.yml
@@ -57,4 +57,6 @@ jobs:
 
       - name: Terraform plan status
         if: steps.plan.outcome == "failure"
-        run: exit 1
+        run: |
+          echo "Workflow gave an error with this file."
+          exit 1
